FROM alpine:3.22

RUN apk add --no-cache ffmpeg
COPY deploy/start-test-publishers.sh /usr/local/bin/start-test-publishers
RUN chmod +x /usr/local/bin/start-test-publishers

ENTRYPOINT ["/usr/local/bin/start-test-publishers"]
